# Generated by Django 5.2.17 on 2026-08-12 20:35
from django.db import migrations, models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_created_at_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='timeout_until',
            field=models.DateTimeField(
                blank=True,
                null=True
            ),
        ),
    ]